### ISSUE TITLE
双拼引入声调拆字和辅码显示不一致疑问

### ISSUE THREAD

**Issue by cuminlo** [mirtlecn/rime-radical-pinyin#10]
### 基本信息

- 使用 [iDvel/rime-ice](https://github.com/iDvel/rime-ice) 配置
- 使用自然码双拼
- `build` 目录已经引入声调

### 配置信息

```
double_pinyin.custom.yaml
patch:
  menu/page_size: 9
  radical_reverse_lookup/dictionary: pinyin
```

```
radical_pinyin.custom.yaml
patch:
  speller/algebra:
    __include: radical_pinyin.schema.yaml:/algebra_double_pinyin
```

### 现象
当我使用 `uU` 拆字时，声调确实已经显示了
<img width="150" alt="image" src="https://github.com/mirtlecn/rime-radical-pinyin/assets/4970189/0ce487a6-4510-4500-8dd6-a17df02ea131">

但是当我使用 ` 辅码时
<img width="133" alt="image" src="https://github.com/mirtlecn/rime-radical-pinyin/assets/4970189/3d95411c-8f7b-41a2-a84c-e9d6cf62625f">
又不显示声调了

### 疑问
按 `iDvel` 文档说的反查和辅码不都是引用你的配置么？那我理解反查和辅码应该是一样的功能吧，为啥会出现两个现象不一样呢？

我刚接触rime没多久，可能理解错误，如果希望自然码双拼使用反查和辅码时都显示声调应该如何配置呢？
