### ISSUE TITLE
关于反查辅助码使用的字典，可否自行替换

### ISSUE THREAD

**Issue by Tback1** [mirtlecn/rime-radical-pinyin#11]
我手工制作了一份笔顺的码表 `radical_stroke.dict.yaml`，想要挂载到反查作为辅助码使用
（现在使用的是雾凇拼音方案，将 `radical` 作为反查辅助使用）

我想不改动 `radical_pinyin.dict.yaml`，这样方便以后升级。但找不到可行的方案
**现有验证会造成改动，但可用的方案有**：
**方案一**：✔ 直接将 `radical_stroke.dict.yaml` 的内容整个复制追加到 `radical_pinyin.dict.yaml` 中
**方案二**：✔ 在 `radical_pinyin.dict.yaml` 中 导入  `radical_stroke.dict.yaml`

```yaml
import_tables:
  - radical_stroke # 笔顺反查
```
![image](https://github.com/mirtlecn/rime-radical-pinyin/assets/8872546/95ae5bb0-d85c-4f23-bda0-3a61454a7e16)

**方案三**：❌ 新建一份字典文件 `radical_all.dict.yaml` 整合两份反查字典，另 新建一份 `radical_pinyin.custom.yaml` 以替换字典文件

截图说明编码UTF-8 LF
![image|280](https://github.com/mirtlecn/rime-radical-pinyin/assets/8872546/26d662aa-d4a9-4da5-90d3-120fa48291ac)

### `radical_all.dict.yaml`内容如下
```yaml
# Rime radical dictionary
# encoding: utf-8
#
# 辅助码词库
#

---
name: radical
version: "2024-07-08"
import_tables:
  - radical_pinyin # 拼音反查
  - radical_stroke # 笔顺反查
...
```

### `radical_pinyin.custom.yaml`内容如下
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  modified_time: "Sun Jul  7 04:42:46 2024"
  rime_version: 1.11.2
patch:
  translator/dictionary: radical_all
```
